### ISSUE TITLE
Zmeny v importance

### ISSUE THREAD

**Issue by Sabka** [Ashen-MG/international-interest-in-sport#15]
1. obsah (i)  [Results are displayed with tree decimal digits, the coefficients are calculated with 10 decimal digits and sorted accordingly. The exact values can be viewed in data export. ]
2. Zmeniť nadpis stránky na International Importance
3. Pridať na stránku pod nadpis text: The coefficient measures the interational importance of individual sports for a selected particular country. It sums the estimatd importantce in all included foreign countries for the particular country weighted by their relative country influence.
4. Pri exporte sa ulozi len tato tabulka, ale skutocne hodnoty so vsetkymi desatinnymi miestami?
5. Názov stĺpca: Order zmeniť na Rank
6. Názov stĺpca: Points zmeniť na Ranking Coefficient
7. Názov stĺpca: Code zmeniť na Sport Code

**Comment by misovsky3** [comment]
Zmeny v Country influence #20
