### ISSUE TITLE
Zmeny vo funding

### ISSUE THREAD

**Issue by Sabka** [Ashen-MG/international-interest-in-sport#16]
1. Zmeniť nadpis stránky na Funding
2. Pridať na stránku pod nadpis text: The total estimate value of national funding of individual sports.
3. Niekde umiestniť info o zdroji dát pre danú krajinu (typicky jeden link, alebo niekoľko linkov, môže byť aj voľný text), o roku, z ktorého dáta sú (buď do (i) alebo nad Export data) a o mene, v ktorej sú dáta uvedené (prípadne menu pridať za hlavičku stĺpca Amount, napr. Amount (USD).
4. Ak sa mena presunie do hlavičky tabuľky, alebo nad ňu, možno zmazať stĺpec tabuľky Currency.

**Comment by misovsky3** [comment]
Co sa tyka tretieho to (i) som povodne zamyslal hlavne na tie zdroje. Ale kedze su pre kazdu krajinu ine tak sa budu menit v zavislosti na vybere krajiny. Netreba ich mat teda v databaze?

**Comment by misovsky3** [comment]
Zmeny vo funding #16
