### ISSUE TITLE
Otazka k exportu

### ISSUE THREAD

**Issue by Sabka** [Ashen-MG/international-interest-in-sport#19]
Pri exporte sa ulozi len tato tabulka, ale skutocne hodnoty so vsetkymi desatinnymi miestami?

**Comment by Ashen-MG** [comment]
Teraz sa exportujú také dáta, aké sa zobrazujú, teda aj so zaokrúhleniami etc., vieme to však splitnúť tak aby sa pri exporte vracali neupravené.
