### ISSUE TITLE
Zmeny v Country influence

### ISSUE THREAD

**Issue by Sabka** [Ashen-MG/international-interest-in-sport#20]
1. Zmeniť nadpis stránky na Country Influence
2. The coefficients measure the relative influence of other countries on the selected particular country. The values depend on mutual export and import between the particular country and all other included countries, on the distance between the countries, on neighbourship of countries, on common or similar language, and on common history.  Economic, non-economic and combined (averaged economic and non-economic) relative influence can be viewed.
3. obsah (i) [Sum of the coefficients for each selected country is 1. See (link) for the full methodology. ]
4. Zmeniť nadpis Data displaying na Display mode
5. Zmeniť nadpis Interconnectness type na Influence type

**Comment by misovsky3** [comment]
#27
