### ISSUE TITLE
vlajky ku krajinam

### ISSUE THREAD

**Issue by Sabka** [Ashen-MG/international-interest-in-sport#22]
Pri zobrazovaní krajín v tabuľkách by bolo dobré pre lepšiu vizuálnu percepciu pridať stĺpec s malou vlajkou krajiny do každého riadku.

**Comment by Sabka** [comment]
neviem, ci chceme priamo nejake obrazky ukladat niekde na cloud a pamatat si ich url v DB v tabulke countries, ale nasla som, ze existuju zaujimave online services ktore ponukaju vlaky, napr. toto vyzera obstojne https://flagpedia.net/download/api

**Comment by Ashen-MG** [comment]
Najjednoduchšie bude použiť nejaké verejné API.
https://countryflagsapi.com/ má podporu už pre formát v ktorom máme uložené krajiny v db (3 písmená). Dané obrázky majú 320px, čo je zrejme aj zbytočne veľa.. https://flagpedia.net ponúkajú obrázky aj v menších rozlíšeniach ale nepodporujú náš formát, čiže bolo potrebné tabuľky country rozšíriť o kódy v formáte https://flagcdn.com/en/codes.json

**Comment by Ashen-MG** [comment]
Našiel som už pripravený mapping z alpha 3 kódov (tie máme my v db) do alpha 2 kódov v js takže nie je potrebné nijak modifikovať db a vieme použiť už flagpediu
